Feature/#97 m2 m connection
Insomnia-IT/agreemod_v2 pull request #15
Opened 2024-03-29 15:32 UTC by Nirneen

добавил миграции, сделал один primary key

2024-03-30 00:17 UTC, wotori commented
Проверил накатку миграция вперёд и назад?
У меня не накатилось.

Там где "comment" по замыслу нужно написать в двух словах что миграция делает
типа:

`alembic revision --autogenerate --rev-id=`date '+%Y_%m_%d_%H%M'` -m "badge_direction_table"`

+ возможно создал лишние миграции, по хорошему одна задача - одна миграция, лучше удалить и схлопнуть в одну все что решается в этой задаче.

не понял на основании чего генерируется эта миграция:
[alembic/versions/2024_03_23_2233-2024_03_23_2233_comment.py](https://github.com/Insomnia-IT/agreemod_v2/pull/15/files#diff-45d64c925dab191018ba4808aee4c1540cab7b17f979c840ba3f65f2944d2c2c)

Похоже что ты запустил скрипт при пустой базе, сначало нужно синхронизовать свою базу с алембиком
`alembic upgrade head` а потом уже генерировать миграции

2024-03-30 00:24 UTC, wotori requested changes
Необходимо:
 - удалить все новые миграции
 - синхронизовать свою базу с текущей версией алембика
 - создать новый. один файл миграции к этой задаче
 - убедиться что миграция накатывается вперёд и назад

2024-03-30 00:24 UTC, wotori commented on alembic/versions/2024_03_23_2233-2024_03_23_2233_comment.py
> +    op.create_table('participation',
это повтор создания таблицы которая ранее уже была создана в другом файле миграции

2024-03-30 18:53 UTC, Nirneen commented
убрал лишние миграции, проверил что откатывается вперед и назад

2024-03-31 12:37 UTC, wotori approved these changes
Работает, можно вливать

2024-03-31 12:42 UTC, merged

2024-04-05 18:08 UTC, wotori commented
после влития в main миграции перестали накатываться, ревертнул, нужно подтянуть main и еще раз все проверить