Feature/#11 engagement модель БД для участия
Insomnia-IT/agreemod_v2 pull request #8
Opened 2024-03-11 13:29 UTC by megorlova

Добавлена модель БД для участия, скорректирован справочник статусов участия.

2024-03-12 18:49 UTC, the-livingstone requested changes

2024-03-12 18:49 UTC, the-livingstone commented on app/dictionaries/participation_status.py
>      def to_list(self) -> bool:
Здесь-то тоже надо было поправить статусы

2024-03-12 18:49 UTC, the-livingstone commented on app/db/orm/engagement.py
> +            person=model.person,
здесь должно быть
```
person_id=model.person.notion_id,
direction_id=model.direction.notion_id
```
Ведь именно айдишники мы пишем в таблицу

2024-03-12 18:49 UTC, the-livingstone commented on app/db/orm/engagement.py
> +            f"noiton_id='{self.notion_id}',"
очепятка

2024-03-12 18:49 UTC, the-livingstone commented on app/db/orm/engagement.py
> +            noiton_id=model.notion_id,
снова очепятка

2024-03-12 18:49 UTC, the-livingstone commented on app/db/orm/engagement.py
> +    year: Mapped[int] = Column(Integer, nullable=False) #req
не хватает первичного ключа
```
id: Mapped[int] = Column(Integer, primary_key=True)

2024-03-12 18:49 UTC, the-livingstone commented on app/db/orm/engagement.py
> +            person=self.person,
А здесь должно быть такое:
```
person=self.person.to_model(),
direction=self.direction.to_model(),
participation=self.participation.value,
role=self.role.value,
status=self.status.value
```

2024-03-12 18:49 UTC, the-livingstone commented on app/models/engagement.py
> +class Engagement(DomainModel):
Это BaseModel, потому что у участия нет (или не всегда есть) notion_id

Может всё-таки назовём Participation? А то у нас в трёх местах Participaton, а в двух Engagement

2024-03-13 12:14 UTC, megorlova commented on app/db/orm/engagement.py
> +            person=self.person,
participation=self.participation.value - вот эта строчка точно должна быть? Не пойму, что она тянет

2024-03-13 20:54 UTC, the-livingstone approved these changes

2024-03-13 20:54 UTC, merged