working docker compose, tested on mac
Insomnia-IT/agreemod_v2 pull request #9
Opened 2024-03-16 19:37 UTC by wotori

2024-03-16 21:42 UTC, the-livingstone requested changes

2024-03-16 21:42 UTC, the-livingstone commented on .env.example
> +# POSTGRES__HOST=postgres # не нужно так как определяется в докере - POSTGRES__HOST=postgres
Эта переменная используется sqlalchemy и алембиком, не нужно её убирать из .env

2024-03-16 21:42 UTC, the-livingstone commented on docker-compose.yml
> +      - ./.env:/opt/app/.env
предлагаю сделать отдельный контейнер для управления миграциями и не прилеплять эту функциональность ни к апи ни к апдейтеру

2024-03-16 21:42 UTC, the-livingstone commented on docker/updater.dockerfile
> +RUN poetry config virtualenvs.create false
разумно

2024-03-18 01:38 UTC, wotori commented on .env.example
> +№POSTGRES__HOST=postgres # не нужно так как определяется в докере - POSTGRES__HOST=postgres
вообще я это поле пробросил через докер, поэтому все работает
вернул обратно и сделал пометку что нужно указывать имя контейнера при работе с докер-компоузом
    environment:
      - POSTGRES__HOST=postgres

2024-03-18 01:41 UTC, wotori commented on db/meta.py
> +logger.debug(f"pg settings: {PG_URL}")
это нужно было для разработки, убрал

p.s.
это режим дебага в котором продакшн по идее не запускается, так как это может привести к утечкам информации, ухудшению производительности и повышенному риску безопасности.

2024-03-18 01:41 UTC, wotori commented on docker-compose.yml
> +      - POSTGRES__HOST=postgres
Кого его? в выделеном фрагменте кода убрана пустая строка.
ты про `hostname: ${POSTGRES__HOST}`?
потому что хостнейм не пробрасывается из вне а определяется внутри docker-compose файла

2024-03-18 01:41 UTC, wotori commented on .env.example
> +# POSTGRES__HOST=postgres # не нужно так как определяется в докере - POSTGRES__HOST=postgres
вернул обратно, но при работе с докер-компоуз она не используется из .env файла так как определяется самим docker-compose
```
    environment:
      - POSTGRES__HOST=postgres
```

2024-03-18 01:41 UTC, wotori commented on docker-compose.yml
> +      - ./.env:/opt/app/.env
я бы не стал плодить контейнеры на такие микрозадачи, апдейтер вполне может это сделать при запуске, ему это ничего не стоит так как он все по сути для этого имеет, + тут я заставлял работать то, что не работало

2024-03-18 16:45 UTC, merged